# Generated by Django 4.2.7 on 2023-11-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("preview_image_url", models.URLField(max_length=255)),
                ("content_image_urls", models.JSONField(default=list)),
                ("github_url", models.URLField(max_length=255)),
                ("deployed_project_url", models.URLField(max_length=255)),
            ],
        ),
    ]
