# Generated by Django 4.2.7 on 2023-11-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project", name="preview_url", field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="project", name="project_url", field=models.URLField(blank=True),
        ),
    ]
